[package]
name = "nbs-player-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
nbs-rs = { git = "https://github.com/tomast1337/nbs-rs.git"}
raylib = "5.0.2"
samplerate-rs = "0.1.0"
js-sys = "0.3.77"
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4.50"
wasm-timer = "0.2.5"
web-sys = { version = "0.3.77", features = ["Window", "Document", "Element", "AudioContext", "WebGlRenderingContext", "HtmlCanvasElement", "CanvasRenderingContext2d", "console", "WebGl2RenderingContext", "AudioBufferSourceNode", "AudioBuffer", "AudioDestinationNode", "AudioContextState", "Performance"] }
log = "0.4.26"
colog = "1.3.0"
kira = "0.10.4"
dasp = "0.11.0"
lewton = "0.10.2"
dasp_frame = "0.11.0"


[lib]
crate-type = ["cdylib"]  
