// Generated by `cargo run -p nbs-player-wgpu --example convert_shaders`. Do not edit.
struct Bg {
    iResolution: vec2<f32>,
    iTime: f32,
    speed: f32,
    background_color: vec4<f32>,
    accent_color: vec4<f32>,
    text_color: vec4<f32>,
    white_key_color: vec4<f32>,
    black_key_color: vec4<f32>,
    white_text_key_color: vec4<f32>,
    black_text_key_color: vec4<f32>,
}

struct FragmentOutput {
    @location(0) _fragColor: vec4<f32>,
}

var<private> _fragColor: vec4<f32>;
@group(0) @binding(0) 
var<uniform> global: Bg;
var<private> _fragCoord: vec4<f32>;
var<private> gl_FragCoord_1: vec4<f32>;

fn hash(p: vec2<f32>) -> f32 {
    var p_1: vec2<f32>;

    p_1 = p;
    let _e24 = p_1;
    let _e29 = p_1;
    p_1 = vec2<f32>(dot(_e24, vec2<f32>(127.1f, 311.7f)), dot(_e29, vec2<f32>(269.5f, 183.3f)));
    let _e35 = p_1;
    let _e37 = p_1;
    return fract((sin((_e35.x + _e37.y)) * 43758.547f));
}

fn noise(p_2: vec2<f32>) -> f32 {
    var p_3: vec2<f32>;
    var i: vec2<f32>;
    var f: vec2<f32>;

    p_3 = p_2;
    let _e24 = p_3;
    i = floor(_e24);
    let _e27 = p_3;
    f = fract(_e27);
    let _e30 = i;
    let _e35 = hash((_e30 + vec2<f32>(0f, 0f)));
    let _e36 = i;
    let _e41 = hash((_e36 + vec2<f32>(1f, 0f)));
    let _e42 = f;
    let _e45 = i;
    let _e50 = hash((_e45 + vec2<f32>(0f, 1f)));
    let _e51 = i;
    let _e56 = hash((_e51 + vec2<f32>(1f, 1f)));
    let _e57 = f;
    let _e60 = f;
    return mix(mix(_e35, _e41, _e42.x), mix(_e50, _e56, _e57.x), _e60.y);
}

fn _nbs_main() {
    var uv: vec2<f32>;
    var t: f32;
    var flameBase: f32;
    var n: f32;
    var flame: f32;
    var flameColor: vec3<f32>;
    var flicker: f32;
    var alpha: f32;

    let _e22 = _fragCoord;
    let _e30 = global.iResolution;
    uv = ((floor((_e22.xy / vec2(10f))) * 10f) / _e30.xy);
    let _e35 = uv;
    let _e37 = global.iResolution;
    let _e39 = global.iResolution;
    uv.x = (_e35.x * (_e37.x / _e39.y));
    let _e43 = global.iTime;
    let _e44 = global.speed;
    t = (_e43 * _e44);
    let _e48 = uv;
    let _e50 = t;
    uv.y = (_e48.y - (_e50 * 0.4f));
    let _e55 = uv;
    let _e57 = uv;
    let _e61 = t;
    uv.x = (_e55.x + (sin(((_e57.y * 2f) + _e61)) * 0.1f));
    let _e68 = uv;
    flameBase = (1f - _e68.y);
    let _e72 = uv;
    let _e76 = uv;
    let _e80 = t;
    let _e83 = noise(vec2<f32>((_e72.x * 4f), ((_e76.y * 2f) + _e80)));
    n = _e83;
    let _e85 = n;
    let _e86 = uv;
    let _e90 = uv;
    let _e94 = t;
    let _e99 = noise(vec2<f32>((_e86.x * 8f), ((_e90.y * 4f) + (_e94 * 1.5f))));
    n = (_e85 + (_e99 * 0.5f));
    let _e103 = n;
    n = (_e103 / 1.5f);
    let _e106 = n;
    n = clamp(_e106, 0f, 1f);
    let _e110 = flameBase;
    let _e111 = n;
    flame = (_e110 * _e111);
    let _e114 = flame;
    flame = (floor((_e114 * 4f)) / 4f);
    let _e120 = global.background_color;
    let _e122 = global.accent_color;
    let _e124 = flame;
    flameColor = mix(_e120.xyz, _e122.xyz, vec3(_e124));
    let _e128 = uv;
    let _e132 = t;
    let _e136 = noise(vec2<f32>((_e128.x * 6f), (_e132 * 3f)));
    flicker = _e136;
    let _e138 = flameColor;
    let _e139 = flicker;
    let _e144 = uv;
    flameColor = (_e138 + (vec3((_e139 * 0.2f)) * (1f - _e144.y)));
    let _e149 = flameColor;
    flameColor = clamp(_e149, vec3(0f), vec3(1f));
    let _e157 = flameBase;
    alpha = smoothstep(0.1f, 0.6f, _e157);
    let _e160 = flameColor;
    let _e161 = alpha;
    flameColor = (_e160 * _e161);
    let _e163 = flameColor;
    _fragColor = vec4<f32>(_e163.x, _e163.y, _e163.z, 1f);
    return;
}

fn main_1() {
    let _e23 = gl_FragCoord_1;
    let _e25 = global.iResolution;
    let _e27 = gl_FragCoord_1;
    let _e30 = gl_FragCoord_1;
    let _e31 = _e30.zw;
    _fragCoord = vec4<f32>(_e23.x, (_e25.y - _e27.y), _e31.x, _e31.y);
    _nbs_main();
    return;
}

@fragment 
fn main(@builtin(position) gl_FragCoord: vec4<f32>) -> FragmentOutput {
    gl_FragCoord_1 = gl_FragCoord;
    main_1();
    let _e27 = _fragColor;
    return FragmentOutput(_e27);
}
