// Generated by `cargo run -p nbs-player-wgpu --example convert_shaders`. Do not edit.
struct Bg {
    iResolution: vec2<f32>,
    iTime: f32,
    speed: f32,
    background_color: vec4<f32>,
    accent_color: vec4<f32>,
    text_color: vec4<f32>,
    white_key_color: vec4<f32>,
    black_key_color: vec4<f32>,
    white_text_key_color: vec4<f32>,
    black_text_key_color: vec4<f32>,
}

struct FragmentOutput {
    @location(0) _fragColor: vec4<f32>,
}

var<private> _fragColor: vec4<f32>;
@group(0) @binding(0) 
var<uniform> global: Bg;
var<private> _fragCoord: vec4<f32>;
var<private> gl_FragCoord_1: vec4<f32>;

fn hash2to1_(p: vec2<f32>) -> f32 {
    var p_1: vec2<f32>;
    var p3_: vec3<f32>;

    p_1 = p;
    let _e24 = p_1;
    p3_ = fract((vec3<f32>(_e24.xyx) * 0.1031f));
    let _e31 = p3_;
    let _e32 = p3_;
    let _e33 = p3_;
    p3_ = (_e31 + vec3(dot(_e32, (_e33.yzx + vec3(33.33f)))));
    let _e41 = p3_;
    let _e43 = p3_;
    let _e46 = p3_;
    return fract(((_e41.x + _e43.y) * _e46.z));
}

fn hash3to1_(p3_1: vec3<f32>) -> f32 {
    var p3_2: vec3<f32>;

    p3_2 = p3_1;
    let _e24 = p3_2;
    p3_2 = fract((_e24 * 0.1031f));
    let _e28 = p3_2;
    let _e29 = p3_2;
    let _e30 = p3_2;
    p3_2 = (_e28 + vec3(dot(_e29, (_e30.zyx + vec3(31.32f)))));
    let _e38 = p3_2;
    let _e40 = p3_2;
    let _e43 = p3_2;
    return fract(((_e38.x + _e40.y) * _e43.z));
}

fn FlowerCenter(uv: vec2<f32>) -> f32 {
    var uv_1: vec2<f32>;
    var pixUV: vec2<f32>;

    uv_1 = uv;
    let _e24 = uv_1;
    pixUV = (floor((_e24 / vec2(0.125f))) * 0.125f);
    let _e32 = pixUV;
    let _e33 = hash2to1_(_e32);
    return ceil((_e33 - 0.995f));
}

fn FlowerNeighbor(uv_2: vec2<f32>) -> f32 {
    var uv_3: vec2<f32>;
    var offset: vec2<f32> = vec2<f32>(0f, 0.125f);

    uv_3 = uv_2;
    let _e29 = uv_3;
    let _e30 = offset;
    let _e33 = FlowerCenter((_e29 + _e30.xy));
    let _e34 = uv_3;
    let _e35 = offset;
    let _e38 = FlowerCenter((_e34 - _e35.xy));
    let _e39 = uv_3;
    let _e40 = offset;
    let _e43 = FlowerCenter((_e39 + _e40.yx));
    let _e44 = uv_3;
    let _e45 = offset;
    let _e48 = FlowerCenter((_e44 - _e45.yx));
    return max(_e33, max(_e38, max(_e43, _e48)));
}

fn FlowerShadow(uv_4: vec2<f32>) -> f32 {
    var uv_5: vec2<f32>;
    var offset_1: vec3<f32> = vec3<f32>(-0.125f, 0.125f, 0f);

    uv_5 = uv_4;
    let _e31 = uv_5;
    let _e32 = offset_1;
    let _e37 = FlowerCenter((_e31 + (_e32.zy * 2f)));
    let _e38 = uv_5;
    let _e39 = offset_1;
    let _e42 = FlowerCenter((_e38 + _e39.yy));
    let _e43 = uv_5;
    let _e44 = offset_1;
    let _e47 = FlowerCenter((_e43 + _e44.xy));
    return max(_e37, max(_e42, _e47));
}

fn _nbs_main() {
    var uv_6: vec2<f32>;
    var subuv: vec2<f32>;
    var coord: vec2<f32>;
    var noiseForTime: f32;
    var sinTime: f32;
    var subuvx: f32;
    var noiseForBottom: f32;
    var isBottomPixel: f32;
    var grassPieceUV: vec2<f32>;
    var noiseForGrassPiece: f32;
    var noise: f32;
    var gray: f32;
    var col: vec3<f32>;
    var flowerNeighbor: f32;
    var flower: f32;
    var flowerShadow: f32;

    let _e22 = _fragCoord;
    let _e24 = global.iResolution;
    uv_6 = (_e22.xy / vec2(_e24.y));
    let _e29 = uv_6;
    uv_6 = (_e29 * 10f);
    let _e33 = uv_6;
    let _e35 = global.iTime;
    let _e36 = global.speed;
    uv_6.y = (_e33.y + (_e35 * _e36));
    let _e39 = uv_6;
    subuv = fract(_e39);
    let _e42 = uv_6;
    coord = floor(_e42);
    let _e45 = coord;
    let _e46 = hash2to1_(_e45);
    let _e47 = subuv;
    noiseForTime = (_e46 + (floor(((_e47.x - 0.5f) / 0.125f)) * 0.125f));
    let _e58 = global.iTime;
    let _e59 = global.speed;
    let _e61 = noiseForTime;
    sinTime = (floor(((sin(((_e58 * _e59) + _e61)) * 0.2f) / 0.125f)) * 0.125f);
    let _e72 = subuv;
    let _e74 = sinTime;
    subuvx = (floor(((_e72.x + _e74) / 0.125f)) * 0.125f);
    let _e82 = coord;
    let _e83 = subuvx;
    let _e87 = hash3to1_(vec3<f32>(_e82.x, _e82.y, _e83));
    noiseForBottom = _e87;
    let _e90 = noiseForBottom;
    let _e95 = subuv;
    isBottomPixel = (1f - max(ceil((_e90 - 0.3f)), step(0.125f, _e95.y)));
    let _e102 = coord;
    let _e104 = isBottomPixel;
    coord.y = (_e102.y - _e104);
    let _e106 = uv_6;
    let _e108 = sinTime;
    let _e110 = uv_6;
    grassPieceUV = vec2<f32>((_e106.x + _e108), (_e110.y * 0.5f));
    let _e116 = grassPieceUV;
    let _e123 = hash2to1_((floor((_e116 / vec2(0.125f))) * 0.125f));
    noiseForGrassPiece = ceil((_e123 - 0.95f));
    let _e128 = noiseForGrassPiece;
    let _e129 = noiseForGrassPiece;
    noiseForGrassPiece = (_e128 * (((_e129 * 2f) - 1f) * 0.25f));
    let _e137 = coord;
    let _e138 = hash2to1_(_e137);
    let _e139 = noiseForGrassPiece;
    noise = (_e138 + _e139);
    let _e142 = noise;
    gray = (ceil((_e142 * 4f)) / 4f);
    let _e149 = global.background_color;
    let _e151 = global.accent_color;
    let _e153 = gray;
    col = mix(_e149.xyz, _e151.xyz, vec3(_e153));
    let _e157 = col;
    let _e158 = global.black_key_color;
    let _e161 = gray;
    col = mix(_e157, _e158.xyz, vec3((0.2f * _e161)));
    let _e165 = col;
    let _e166 = global.white_key_color;
    let _e170 = gray;
    col = mix(_e165, _e166.xyz, vec3((0.1f * (1f - _e170))));
    let _e175 = uv_6;
    let _e176 = FlowerNeighbor(_e175);
    flowerNeighbor = _e176;
    let _e178 = col;
    let _e179 = global.text_color;
    let _e181 = flowerNeighbor;
    col = mix(_e178, _e179.xyz, vec3((_e181 * 0.7f)));
    let _e186 = uv_6;
    let _e187 = FlowerCenter(_e186);
    flower = _e187;
    let _e189 = col;
    let _e190 = global.white_text_key_color;
    let _e192 = flower;
    col = mix(_e189, _e190.xyz, vec3(_e192));
    let _e195 = uv_6;
    let _e196 = FlowerShadow(_e195);
    flowerShadow = _e196;
    let _e198 = col;
    let _e199 = col;
    let _e203 = flowerShadow;
    col = mix(_e198, (_e199 - vec3(0.15f)), vec3(_e203));
    let _e206 = col;
    _fragColor = vec4<f32>(_e206.x, _e206.y, _e206.z, 1f);
    return;
}

fn main_1() {
    let _e23 = gl_FragCoord_1;
    let _e25 = global.iResolution;
    let _e27 = gl_FragCoord_1;
    let _e30 = gl_FragCoord_1;
    let _e31 = _e30.zw;
    _fragCoord = vec4<f32>(_e23.x, (_e25.y - _e27.y), _e31.x, _e31.y);
    _nbs_main();
    return;
}

@fragment 
fn main(@builtin(position) gl_FragCoord: vec4<f32>) -> FragmentOutput {
    gl_FragCoord_1 = gl_FragCoord;
    main_1();
    let _e27 = _fragColor;
    return FragmentOutput(_e27);
}
