// Generated by `cargo run -p nbs-player-wgpu --example convert_shaders`. Do not edit.
struct Bg {
    iResolution: vec2<f32>,
    iTime: f32,
    speed: f32,
    background_color: vec4<f32>,
    accent_color: vec4<f32>,
    text_color: vec4<f32>,
    white_key_color: vec4<f32>,
    black_key_color: vec4<f32>,
    white_text_key_color: vec4<f32>,
    black_text_key_color: vec4<f32>,
}

struct FragmentOutput {
    @location(0) _fragColor: vec4<f32>,
}

var<private> _fragColor: vec4<f32>;
@group(0) @binding(0) 
var<uniform> global: Bg;
var<private> _fragCoord: vec4<f32>;
var<private> gl_FragCoord_1: vec4<f32>;

fn hash(p: vec3<f32>) -> vec3<f32> {
    var p_1: vec3<f32>;

    p_1 = p;
    let _e24 = p_1;
    let _e30 = p_1;
    let _e36 = p_1;
    p_1 = vec3<f32>(dot(_e24, vec3<f32>(127.1f, 311.7f, 74.7f)), dot(_e30, vec3<f32>(269.5f, 183.3f, 246.1f)), dot(_e36, vec3<f32>(113.5f, 271.9f, 124.6f)));
    let _e46 = p_1;
    p_1 = (vec3(-1f) + (2f * fract((sin(_e46) * 43758.547f))));
    let _e54 = p_1;
    return _e54;
}

fn noise(p_2: vec3<f32>) -> f32 {
    var p_3: vec3<f32>;
    var i: vec3<f32>;
    var f: vec3<f32>;
    var u: vec3<f32>;

    p_3 = p_2;
    let _e24 = p_3;
    i = floor(_e24);
    let _e27 = p_3;
    f = fract(_e27);
    let _e30 = f;
    let _e31 = f;
    let _e35 = f;
    u = ((_e30 * _e31) * (vec3(3f) - (2f * _e35)));
    let _e41 = i;
    let _e47 = hash((_e41 + vec3<f32>(0f, 0f, 0f)));
    let _e48 = f;
    let _e55 = i;
    let _e61 = hash((_e55 + vec3<f32>(1f, 0f, 0f)));
    let _e62 = f;
    let _e69 = u;
    let _e72 = i;
    let _e78 = hash((_e72 + vec3<f32>(0f, 1f, 0f)));
    let _e79 = f;
    let _e86 = i;
    let _e92 = hash((_e86 + vec3<f32>(1f, 1f, 0f)));
    let _e93 = f;
    let _e100 = u;
    let _e103 = u;
    let _e106 = i;
    let _e112 = hash((_e106 + vec3<f32>(0f, 0f, 1f)));
    let _e113 = f;
    let _e120 = i;
    let _e126 = hash((_e120 + vec3<f32>(1f, 0f, 1f)));
    let _e127 = f;
    let _e134 = u;
    let _e137 = i;
    let _e143 = hash((_e137 + vec3<f32>(0f, 1f, 1f)));
    let _e144 = f;
    let _e151 = i;
    let _e157 = hash((_e151 + vec3<f32>(1f, 1f, 1f)));
    let _e158 = f;
    let _e165 = u;
    let _e168 = u;
    let _e171 = u;
    return mix(mix(mix(dot(_e47, (_e48 - vec3<f32>(0f, 0f, 0f))), dot(_e61, (_e62 - vec3<f32>(1f, 0f, 0f))), _e69.x), mix(dot(_e78, (_e79 - vec3<f32>(0f, 1f, 0f))), dot(_e92, (_e93 - vec3<f32>(1f, 1f, 0f))), _e100.x), _e103.y), mix(mix(dot(_e112, (_e113 - vec3<f32>(0f, 0f, 1f))), dot(_e126, (_e127 - vec3<f32>(1f, 0f, 1f))), _e134.x), mix(dot(_e143, (_e144 - vec3<f32>(0f, 1f, 1f))), dot(_e157, (_e158 - vec3<f32>(1f, 1f, 1f))), _e165.x), _e168.y), _e171.z);
}

fn _nbs_main() {
    var uv: vec2<f32>;
    var t: f32;
    var h: f32;
    var n: i32 = 1i;
    var i_1: f32;
    var colorValue: f32;
    var col: vec3<f32>;

    let _e22 = _fragCoord;
    let _e24 = global.iResolution;
    uv = (_e22.xy / _e24.xy);
    let _e28 = global.iTime;
    let _e29 = global.speed;
    t = (_e28 * _e29);
    let _e32 = uv;
    uv = (floor((_e32 * 100f)) / vec2(100f));
    let _e40 = uv;
    let _e42 = global.iResolution;
    let _e44 = global.iResolution;
    uv.x = (_e40.x * (_e42.x / _e44.y));
    let _e48 = uv;
    uv = (_e48 * 5f);
    let _e51 = uv;
    let _e53 = (_e51 * 2f);
    let _e54 = t;
    let _e58 = noise(vec3<f32>(_e53.x, _e53.y, _e54));
    h = _e58;
    loop {
        let _e62 = n;
        if !((_e62 < 5i)) {
            break;
        }
        {
            let _e69 = n;
            i_1 = f32(_e69);
            let _e72 = uv;
            let _e74 = i_1;
            let _e76 = i_1;
            let _e77 = uv;
            let _e80 = i_1;
            let _e82 = t;
            let _e86 = h;
            let _e87 = i_1;
            let _e95 = i_1;
            let _e97 = uv;
            let _e101 = i_1;
            let _e103 = h;
            let _e105 = t;
            let _e110 = i_1;
            uv = (_e72 - vec2<f32>((((0.7f / _e74) * sin(((((_e76 * _e77.y) + _e80) + (_e82 * 5f)) + (_e86 * _e87)))) + 0.8f), (((0.4f / _e95) * sin((((((_e97.x + 4f) - _e101) + _e103) + (_e105 * 5f)) + (0.3f * _e110)))) + 1.6f)));
        }
        continuing {
            let _e66 = n;
            n = (_e66 + 1i);
        }
    }
    let _e119 = uv;
    let _e121 = uv;
    let _e123 = t;
    let _e125 = h;
    let _e132 = uv;
    let _e134 = t;
    let _e137 = h;
    uv = (_e119 - vec2<f32>(((1.2f * sin(((_e121.x + _e123) + _e125))) + 1.8f), ((0.4f * sin(((_e132.y + _e134) + (0.3f * _e137)))) + 1.6f)));
    let _e147 = uv;
    let _e149 = uv;
    colorValue = ((0.5f * sin((_e147.x + _e149.y))) + 0.5f);
    let _e157 = global.background_color;
    let _e159 = global.accent_color;
    let _e161 = colorValue;
    col = mix(_e157.xyz, _e159.xyz, vec3(_e161));
    let _e165 = col;
    _fragColor = vec4<f32>(_e165.x, _e165.y, _e165.z, 1f);
    return;
}

fn main_1() {
    let _e23 = gl_FragCoord_1;
    let _e25 = global.iResolution;
    let _e27 = gl_FragCoord_1;
    let _e30 = gl_FragCoord_1;
    let _e31 = _e30.zw;
    _fragCoord = vec4<f32>(_e23.x, (_e25.y - _e27.y), _e31.x, _e31.y);
    _nbs_main();
    return;
}

@fragment 
fn main(@builtin(position) gl_FragCoord: vec4<f32>) -> FragmentOutput {
    gl_FragCoord_1 = gl_FragCoord;
    main_1();
    let _e27 = _fragColor;
    return FragmentOutput(_e27);
}
