// Generated by `cargo run -p nbs-player-wgpu --example convert_shaders`. Do not edit.
struct Bg {
    iResolution: vec2<f32>,
    iTime: f32,
    speed: f32,
    background_color: vec4<f32>,
    accent_color: vec4<f32>,
    text_color: vec4<f32>,
    white_key_color: vec4<f32>,
    black_key_color: vec4<f32>,
    white_text_key_color: vec4<f32>,
    black_text_key_color: vec4<f32>,
}

struct FragmentOutput {
    @location(0) _fragColor: vec4<f32>,
}

var<private> _fragColor: vec4<f32>;
@group(0) @binding(0) 
var<uniform> global: Bg;
var<private> _fragCoord: vec4<f32>;
var<private> gl_FragCoord_1: vec4<f32>;

fn hash(n: f32) -> f32 {
    var n_1: f32;

    n_1 = n;
    let _e24 = n_1;
    return fract((sin(_e24) * 43758.547f));
}

fn noise(x: vec2<f32>) -> f32 {
    var x_1: vec2<f32>;
    var p: vec2<f32>;
    var f: vec2<f32>;
    var n_2: f32;

    x_1 = x;
    let _e24 = x_1;
    p = floor(_e24);
    let _e27 = x_1;
    f = fract(_e27);
    let _e30 = f;
    let _e31 = f;
    let _e35 = f;
    f = ((_e30 * _e31) * (vec2(3f) - (2f * _e35)));
    let _e40 = p;
    let _e42 = p;
    n_2 = (_e40.x + (_e42.y * 57f));
    let _e48 = n_2;
    let _e51 = hash((_e48 + 0f));
    let _e52 = n_2;
    let _e55 = hash((_e52 + 1f));
    let _e56 = f;
    let _e59 = n_2;
    let _e62 = hash((_e59 + 57f));
    let _e63 = n_2;
    let _e66 = hash((_e63 + 58f));
    let _e67 = f;
    let _e70 = f;
    return mix(mix(_e51, _e55, _e56.x), mix(_e62, _e66, _e67.x), _e70.y);
}

fn map(p_1: vec2<f32>, offset: f32) -> vec2<f32> {
    var p_2: vec2<f32>;
    var offset_1: f32;
    var a: f32;

    p_2 = p_1;
    offset_1 = offset;
    let _e27 = p_2;
    let _e30 = global.iTime;
    let _e31 = global.speed;
    let _e34 = p_2;
    p_2.x = (_e27.x + (0.1f * sin(((_e30 * _e31) + (2f * _e34.y)))));
    let _e42 = p_2;
    let _e45 = global.iTime;
    let _e46 = global.speed;
    let _e49 = p_2;
    p_2.y = (_e42.y + (0.1f * sin(((_e45 * _e46) + (2f * _e49.x)))));
    let _e56 = p_2;
    let _e60 = global.iTime;
    let _e62 = global.speed;
    let _e67 = noise(((_e56 * 1.5f) + vec2(sin(((0.1f * _e60) * _e62)))));
    a = (_e67 * 6.2831f);
    let _e71 = a;
    let _e72 = offset_1;
    a = (_e71 - _e72);
    let _e74 = a;
    let _e76 = a;
    return vec2<f32>(cos(_e74), sin(_e76));
}

fn _nbs_main() {
    var fragCoord: vec2<f32>;
    var p_3: vec2<f32>;
    var uv: vec2<f32>;
    var offset_2: f32;
    var acc: f32 = 0f;
    var col: vec3<f32> = vec3(0f);
    var i: i32 = 0i;
    var dir: vec2<f32>;
    var h: f32;
    var w: f32;
    var blend1_: vec3<f32>;
    var blend2_: vec3<f32>;
    var blend3_: vec3<f32>;
    var blend4_: vec3<f32>;
    var ttt: vec3<f32>;
    var gg: f32;
    var nor: vec3<f32>;
    var di: vec2<f32>;

    let _e22 = _fragCoord;
    fragCoord = _e22.xy;
    let _e25 = fragCoord;
    let _e26 = global.iResolution;
    p_3 = (_e25 / _e26);
    let _e32 = p_3;
    uv = (vec2(-1f) + (2f * _e32));
    let _e38 = uv;
    let _e40 = global.iResolution;
    let _e42 = global.iResolution;
    uv.x = (_e38.x * (_e40.x / _e42.y));
    let _e46 = global.iTime;
    let _e47 = fragCoord;
    let _e49 = global.iResolution;
    offset_2 = (_e46 + (_e47.x / _e49.x));
    loop {
        let _e61 = i;
        if !((_e61 < 32i)) {
            break;
        }
        {
            let _e68 = uv;
            let _e69 = offset_2;
            let _e70 = map(_e68, _e69);
            dir = _e70;
            let _e72 = i;
            h = (f32(_e72) / 32f);
            let _e78 = h;
            let _e81 = h;
            w = ((4f * _e78) * (1f - _e81));
            let _e85 = global.background_color;
            let _e87 = global.accent_color;
            let _e89 = h;
            blend1_ = mix(_e85.xyz, _e87.xyz, vec3(_e89));
            let _e93 = global.text_color;
            let _e95 = global.white_key_color;
            let _e97 = global.iTime;
            let _e98 = i;
            blend2_ = mix(_e93.xyz, _e95.xyz, vec3(((sin((_e97 + f32(_e98))) * 0.5f) + 0.5f)));
            let _e109 = global.black_key_color;
            let _e111 = global.white_text_key_color;
            let _e113 = global.iTime;
            let _e114 = i;
            blend3_ = mix(_e109.xyz, _e111.xyz, vec3(((cos((_e113 + (f32(_e114) * 0.5f))) * 0.5f) + 0.5f)));
            let _e127 = global.black_text_key_color;
            let _e129 = blend1_;
            let _e130 = h;
            blend4_ = mix(_e127.xyz, _e129, vec3(_e130));
            let _e134 = w;
            let _e135 = blend1_;
            let _e136 = blend2_;
            let _e137 = h;
            let _e140 = blend3_;
            let _e141 = blend4_;
            let _e143 = h;
            ttt = (_e134 * mix(mix(_e135, _e136, vec3(_e137)), mix(_e140, _e141, vec3((1f - _e143))), vec3(0.5f)));
            let _e152 = col;
            let _e153 = w;
            let _e154 = ttt;
            col = (_e152 + (_e153 * _e154));
            let _e157 = acc;
            let _e158 = w;
            acc = (_e157 + _e158);
            let _e160 = uv;
            let _e162 = dir;
            uv = (_e160 + (0.008f * _e162));
        }
        continuing {
            let _e65 = i;
            i = (_e65 + 1i);
        }
    }
    let _e165 = col;
    let _e166 = acc;
    col = (_e165 / vec3(_e166));
    let _e169 = col;
    gg = dot(_e169, vec3(0.333f));
    let _e174 = gg;
    let _e175 = dpdx(_e174);
    let _e177 = gg;
    let _e178 = dpdy(_e177);
    nor = normalize(vec3<f32>(_e175, 0.5f, _e178));
    let _e182 = col;
    let _e185 = nor;
    col = (_e182 + (vec3(0.4f) * dot(_e185, vec3<f32>(0.7f, 0.01f, 0.7f))));
    let _e193 = uv;
    let _e194 = offset_2;
    let _e195 = map(_e193, _e194);
    di = _e195;
    let _e197 = col;
    let _e200 = di;
    col = (_e197 * (0.65f + (0.35f * dot(_e200, vec2(0.707f)))));
    let _e207 = col;
    let _e211 = p_3;
    let _e215 = p_3;
    col = (_e207 * (0.2f + (0.8f * pow(((4f * _e211.x) * (1f - _e215.x)), 0.1f))));
    let _e224 = col;
    col = (_e224 * 1.7f);
    let _e227 = col;
    _fragColor = vec4<f32>(_e227.x, _e227.y, _e227.z, 1f);
    return;
}

fn main_1() {
    let _e23 = gl_FragCoord_1;
    let _e25 = global.iResolution;
    let _e27 = gl_FragCoord_1;
    let _e30 = gl_FragCoord_1;
    let _e31 = _e30.zw;
    _fragCoord = vec4<f32>(_e23.x, (_e25.y - _e27.y), _e31.x, _e31.y);
    _nbs_main();
    return;
}

@fragment 
fn main(@builtin(position) gl_FragCoord: vec4<f32>) -> FragmentOutput {
    gl_FragCoord_1 = gl_FragCoord;
    main_1();
    let _e27 = _fragColor;
    return FragmentOutput(_e27);
}
