// Generated by `cargo run -p nbs-player-wgpu --example convert_shaders`. Do not edit.
struct Bg {
    iResolution: vec2<f32>,
    iTime: f32,
    speed: f32,
    background_color: vec4<f32>,
    accent_color: vec4<f32>,
    text_color: vec4<f32>,
    white_key_color: vec4<f32>,
    black_key_color: vec4<f32>,
    white_text_key_color: vec4<f32>,
    black_text_key_color: vec4<f32>,
}

struct FragmentOutput {
    @location(0) _fragColor: vec4<f32>,
}

var<private> _fragColor: vec4<f32>;
@group(0) @binding(0) 
var<uniform> global: Bg;
var<private> _fragCoord: vec4<f32>;
var<private> gl_FragCoord_1: vec4<f32>;

fn hash(p: vec2<f32>) -> vec2<f32> {
    var p_1: vec2<f32>;

    p_1 = p;
    let _e24 = p_1;
    let _e29 = p_1;
    p_1 = vec2<f32>(dot(_e24, vec2<f32>(127.1f, 311.7f)), dot(_e29, vec2<f32>(269.5f, 183.3f)));
    let _e35 = p_1;
    return fract((sin(_e35) * 18.5453f));
}

fn voronoi(x: vec2<f32>) -> vec2<f32> {
    var x_1: vec2<f32>;
    var n: vec2<f32>;
    var f: vec2<f32>;
    var m: vec3<f32> = vec3(8f);
    var j: i32 = -1i;
    var i: i32;
    var g: vec2<f32>;
    var o: vec2<f32>;
    var r: vec2<f32>;
    var d: f32;

    x_1 = x;
    let _e24 = x_1;
    n = floor(_e24);
    let _e27 = x_1;
    f = fract(_e27);
    loop {
        let _e36 = j;
        if !((_e36 <= 1i)) {
            break;
        }
        {
            i = -1i;
            loop {
                let _e46 = i;
                if !((_e46 <= 1i)) {
                    break;
                }
                {
                    let _e53 = i;
                    let _e55 = j;
                    g = vec2<f32>(f32(_e53), f32(_e55));
                    let _e59 = n;
                    let _e60 = g;
                    let _e62 = hash((_e59 + _e60));
                    o = _e62;
                    let _e64 = g;
                    let _e65 = f;
                    let _e69 = global.iTime;
                    let _e70 = global.speed;
                    let _e73 = o;
                    r = ((_e64 - _e65) + (vec2(0.5f) + (0.5f * sin((vec2((_e69 * _e70)) + (6.2831f * _e73))))));
                    let _e83 = r;
                    let _e84 = r;
                    d = dot(_e83, _e84);
                    let _e87 = d;
                    let _e88 = m;
                    if (_e87 < _e88.x) {
                        let _e91 = d;
                        let _e92 = o;
                        m = vec3<f32>(_e91, _e92.x, _e92.y);
                    }
                }
                continuing {
                    let _e50 = i;
                    i = (_e50 + 1i);
                }
            }
        }
        continuing {
            let _e40 = j;
            j = (_e40 + 1i);
        }
    }
    let _e96 = m;
    let _e99 = m;
    let _e101 = m;
    return vec2<f32>(sqrt(_e96.x), (_e99.y + _e101.z));
}

fn _nbs_main() {
    var uv: vec2<f32>;
    var scrollUV: vec2<f32>;
    var c: vec2<f32>;
    var base: vec3<f32>;
    var keyMix: vec3<f32>;
    var edge: f32;
    var color: vec3<f32>;

    let _e22 = _fragCoord;
    let _e24 = global.iResolution;
    uv = (_e22.xy / _e24.xy);
    let _e29 = uv;
    let _e31 = global.iResolution;
    let _e33 = global.iResolution;
    uv.x = (_e29.x * (_e31.x / _e33.y));
    let _e37 = uv;
    let _e39 = uv;
    let _e41 = global.iTime;
    let _e42 = global.speed;
    scrollUV = vec2<f32>(_e37.x, (_e39.y + ((_e41 * _e42) * 0.25f)));
    let _e50 = scrollUV;
    let _e52 = voronoi((12f * _e50));
    c = _e52;
    let _e54 = global.background_color;
    let _e56 = global.accent_color;
    let _e60 = c;
    base = mix(_e54.xyz, _e56.xyz, vec3(smoothstep(0f, 1f, _e60.y)));
    let _e66 = global.white_key_color;
    let _e68 = global.black_key_color;
    let _e72 = c;
    keyMix = mix(_e66.xyz, _e68.xyz, vec3(smoothstep(0f, 1f, _e72.y)));
    let _e81 = c;
    edge = (1f - smoothstep(0.08f, 0.12f, _e81.x));
    let _e86 = base;
    let _e88 = c;
    let _e94 = edge;
    let _e95 = keyMix;
    color = ((_e86 * (1f - (_e88.x * 0.4f))) + (_e94 * _e95));
    let _e99 = color;
    _fragColor = vec4<f32>(_e99.x, _e99.y, _e99.z, 1f);
    return;
}

fn main_1() {
    let _e23 = gl_FragCoord_1;
    let _e25 = global.iResolution;
    let _e27 = gl_FragCoord_1;
    let _e30 = gl_FragCoord_1;
    let _e31 = _e30.zw;
    _fragCoord = vec4<f32>(_e23.x, (_e25.y - _e27.y), _e31.x, _e31.y);
    _nbs_main();
    return;
}

@fragment 
fn main(@builtin(position) gl_FragCoord: vec4<f32>) -> FragmentOutput {
    gl_FragCoord_1 = gl_FragCoord;
    main_1();
    let _e27 = _fragColor;
    return FragmentOutput(_e27);
}
