// Generated by `cargo run -p nbs-player-wgpu --example convert_shaders`. Do not edit.
struct Bg {
    iResolution: vec2<f32>,
    iTime: f32,
    speed: f32,
    background_color: vec4<f32>,
    accent_color: vec4<f32>,
    text_color: vec4<f32>,
    white_key_color: vec4<f32>,
    black_key_color: vec4<f32>,
    white_text_key_color: vec4<f32>,
    black_text_key_color: vec4<f32>,
}

struct FragmentOutput {
    @location(0) _fragColor: vec4<f32>,
}

var<private> _fragColor: vec4<f32>;
@group(0) @binding(0) 
var<uniform> global: Bg;
var<private> _fragCoord: vec4<f32>;
var<private> gl_FragCoord_1: vec4<f32>;

fn sphere(coord: vec2<f32>, pos: vec2<f32>, r: f32) -> f32 {
    var coord_1: vec2<f32>;
    var pos_1: vec2<f32>;
    var r_1: f32;
    var d: vec2<f32>;

    coord_1 = coord;
    pos_1 = pos;
    r_1 = r;
    let _e28 = pos_1;
    let _e29 = coord_1;
    d = (_e28 - _e29);
    let _e34 = d;
    let _e35 = d;
    let _e37 = r_1;
    let _e38 = r_1;
    return smoothstep(60f, 0f, (dot(_e34, _e35) - (_e37 * _e38)));
}

fn _nbs_main() {
    var fragCoord: vec2<f32>;
    var uv: vec2<f32>;
    var clamped_uv: vec2<f32>;
    var value: f32;
    var stripe: f32;
    var baseStripe: f32;
    var col: vec3<f32>;
    var glow: f32;
    var pulseColor: vec3<f32>;

    let _e22 = _fragCoord;
    fragCoord = _e22.xy;
    let _e25 = fragCoord;
    let _e26 = global.iResolution;
    uv = (_e25 / _e26.xy);
    let _e30 = fragCoord;
    let _e40 = global.iResolution;
    clamped_uv = ((floor(((_e30 / vec2(30f)) + vec2(0.5f))) * 30f) / _e40.xy);
    let _e44 = clamped_uv;
    value = fract((sin((_e44.x * 10f)) * 43758.547f));
    let _e53 = uv;
    let _e57 = global.iTime;
    let _e59 = value;
    let _e64 = global.speed;
    let _e67 = value;
    let _e68 = (((_e53.y * 0.5f) + ((_e57 * (0.25f + (_e59 / 5f))) * _e64)) + _e67);
    stripe = (_e68 - (floor((_e68 / 0.5f)) * 0.5f));
    let _e76 = stripe;
    baseStripe = (1f - _e76);
    let _e79 = global.text_color;
    let _e81 = global.white_key_color;
    let _e84 = clamped_uv;
    let _e87 = (_e84.x * 10f);
    col = mix(_e79.xyz, _e81.xyz, vec3(step(0.5f, (_e87 - (floor((_e87 / 2f)) * 2f)))));
    let _e97 = col;
    let _e98 = global.black_key_color;
    let _e101 = clamped_uv;
    let _e104 = (_e101.x * 10f);
    col = mix(_e97, _e98.xyz, vec3(step(1f, (_e104 - (floor((_e104 / 2f)) * 2f)))));
    let _e113 = col;
    let _e114 = baseStripe;
    col = (_e113 * _e114);
    let _e116 = fragCoord;
    let _e117 = clamped_uv;
    let _e121 = stripe;
    let _e124 = global.iResolution;
    let _e129 = sphere(_e116, vec2<f32>(_e117.x, ((1f - (2f * _e121)) * _e124.y)), 0.9f);
    glow = _e129;
    let _e131 = global.white_text_key_color;
    let _e133 = global.black_text_key_color;
    let _e135 = value;
    pulseColor = mix(_e131.xyz, _e133.xyz, vec3(_e135));
    let _e139 = col;
    let _e140 = global.accent_color;
    let _e142 = glow;
    let _e146 = pulseColor;
    let _e147 = glow;
    col = (_e139 + (((_e140.xyz * _e142) * 0.5f) + ((_e146 * _e147) * 0.3f)));
    let _e153 = col;
    let _e154 = global.background_color;
    col = mix(_e153, _e154.xyz, vec3(0.5f));
    let _e159 = col;
    _fragColor = vec4<f32>(_e159.x, _e159.y, _e159.z, 1f);
    return;
}

fn main_1() {
    let _e23 = gl_FragCoord_1;
    let _e25 = global.iResolution;
    let _e27 = gl_FragCoord_1;
    let _e30 = gl_FragCoord_1;
    let _e31 = _e30.zw;
    _fragCoord = vec4<f32>(_e23.x, (_e25.y - _e27.y), _e31.x, _e31.y);
    _nbs_main();
    return;
}

@fragment 
fn main(@builtin(position) gl_FragCoord: vec4<f32>) -> FragmentOutput {
    gl_FragCoord_1 = gl_FragCoord;
    main_1();
    let _e27 = _fragColor;
    return FragmentOutput(_e27);
}
