//! GLSL background shader -> WGSL, shared by the `convert_shaders` example and the
//! up-to-date test. naga's GLSL front end does not build for wasm, so the web (and native)
//! builds ship the generated WGSL instead.
//!
//! Included with `#[path]`; expects the `nbs_player_wgpu` crate and `naga` in scope.

use nbs_player_core::config::BackgroundType;

pub const ALL: [(BackgroundType, &str); 8] = [
    (BackgroundType::Plain, "plain"),
    (BackgroundType::Water, "water"),
    (BackgroundType::WaterFall, "water_fall"),
    (BackgroundType::Plasma, "plasma"),
    (BackgroundType::Fire, "fire"),
    (BackgroundType::Grass, "grass"),
    (BackgroundType::Sand, "sand"),
    (BackgroundType::Voronoise, "voronoise"),
];

pub fn to_wgsl(kind: &BackgroundType) -> String {
    let glsl = nbs_player_wgpu::background::fragment_glsl(kind);
    let module = naga::front::glsl::Frontend::default()
        .parse(&naga::front::glsl::Options::from(naga::ShaderStage::Fragment), &glsl)
        .unwrap_or_else(|e| panic!("glsl parse ({kind:?}): {e:?}"));
    let info = naga::valid::Validator::new(
        naga::valid::ValidationFlags::all(),
        naga::valid::Capabilities::all(),
    )
    .validate(&module)
    .unwrap_or_else(|e| panic!("validate ({kind:?}): {e:?}"));
    let wgsl = naga::back::wgsl::write_string(&module, &info, naga::back::wgsl::WriterFlags::empty())
        .unwrap_or_else(|e| panic!("wgsl out ({kind:?}): {e:?}"));
    format!("// Generated by `cargo run -p nbs-player-wgpu --example convert_shaders`. Do not edit.\n{wgsl}")
}
