[package]
name = "nbs-player-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = "0.15.3"
console_error_panic_hook = "0.1.7"
console_log = "1.0.0"
glow = "0.16.0"
js-sys = "0.3.77"
log = "0.4.26"
nbs-rs = { git = "https://github.com/tomast1337/nbs-rs.git"}
pixels = { version = "0.15.0"}
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4.50"
wasm-timer = "0.2.5"
web-sys = { version = "0.3.77", features = ["Window", "Document", "Element", "AudioContext", "WebGlRenderingContext", "HtmlCanvasElement", "CanvasRenderingContext2d", "console", "WebGl2RenderingContext", "AudioBufferSourceNode", "AudioBuffer", "AudioDestinationNode", "AudioContextState", "Performance"] }


[lib]
crate-type = ["cdylib"]  
